### ISSUE TITLE
compiling on Linux met-Lenovo-Y50-70 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### ISSUE THREAD

**Issue by metracy** [egonw/ropenphacts#1]
Tried to compile with groovy, I got this error:

Caught: java.lang.NoClassDefFoundError: org/apache/tools/ant/BuildLogger
java.lang.NoClassDefFoundError: org/apache/tools/ant/BuildLogger
    at build.class$(build.groovy)
    at build.$get$$class$groovy$util$AntBuilder(build.groovy)
    at build.run(build.groovy:1)

**Comment by egonw** [comment]
Mmm... there seems to be missing some class in your Ubuntu system. Can you try the following and then try to build again?

```
> sudo apt-get install r-cran-rjava groovy ant-contrib
```

I'm hoping that that will install the missing class, but not sure...

**Comment by egonw** [comment]
Oi... that was already August??

Well, I seem to have similar issues myself and I expect R and/or RJava update issues...

**Comment by egonw** [comment]
Just tried on my new 64bit Debian GNU/Linux (similar to Ubuntu), and it seems to work if you have Ant installed.
